dicoEcritures = {"DENIS LUCA": "DENIS Lucas",
                 "BOUVIER": "BOUVIER Léo",
                 "DELAGNEAU AERYSS": "DELAGNEAU Aeryss",
                 "SERVAS BENOIT": "SERVAS Benoit",
                 "LAY": "LAY Céline",
                 "MENDES": "MENDES Elisa",
                 "GHIRARDO-HUERDO": "GHIRARDO COURCIER",
                 "COURCIER": "GHIRARDO COURCIER",
                 "BERNARD": "BERNARD Antoine",
                 "ROBERT MOUSSIER": "MOUSSIER Robert",
                 "PEYRAT ALBAN": "PEYRAT Alban",
                 "BLOSSIER MATHILDE": "BLOSSIER Mathilde",
                 "VEURE": "VEURE Loic",
                 "NICITA": "NICITA Gabriele",
                 "DENIERE": "DENIERE Elise",
                 "ASSOCIE": "Comptes Associés",
                 "COMPTE COURANT": "Comptes Associés",
                 "KILOMETRIQUE": "Frais Kilomètriques",
                 "KILOMETRES": "Frais Kilomètriques",
                 "SYND BILLAUDEL": "SYND BILLAUDEL",
                 "SYND ACTIIM": "ACTIIM",
                 "SYND JACQUART": "JACQUART GESTION",
                 "SYNDICAT 26": "Syndic Ste Luce",
                 "SYND BORE": "BORE",
                 "SYND LOFT ONE": "LOFT ONE",
                 "BOUYGUES TELECOM ": "BOUYGUES",
                 "LEROY MERL": "LEROY MERLIN",
                 "MUTUELLE DE POITIERS ": "MUTUELLE DE POITIERS",
                 "EASYPARK": "EASYPARK",
                 "INFOGREFFE": "GREFFE",
                 "LAPEYRE": "LAPEYRE",
                 "CHROMADIS": "CHROMADIS",
                 "EURL DRS": "ELECTRICIEN",
                 "CAF DE": "CAF",
                 "AUCHAN": "AUCHAN",
                 "GPDIS": "MDA",
                 "EPS 33": "EPS 33",
                 "POSTE": "LA POSTE",
                 "REPAR STORE": "REPAR STORES",
                 "BUT": "BUT",
                 "DARTY": "DARTY",
                 "BOULANGER": "BOULANGER",
                 "SUPSOFT": "SUPSOFT",
                 "ORANGE": "ORANGE",
                 "FREE TELECOM": "FREE TELECOM",
                 "IMPOT": "IMPÔTS",
                 "AREVCO": "AREVCO",
                 "TOP SERVICE": "TOP SERVICE",
                 "ICONCEPT": "ICONCEPT",
                 "CCVP ENERGIE": "CCVP ENERGIE",
                 "LA BELLE EPOQUE": "Restaurant",
                 "CASA": "Restaurant",
                 "RESTAURATION": "Restaurant",
                 "BISTROT": "Restaurant",
                 "FILLE DU": "Restaurant",
                 "PERRIER": "Restaurant",
                 "VALJO": "Restaurant",
                 "PERCUES COTISATION": "BNP"
                 }


dicoCategories = [(1, 'Locataire', 'divers', 1),
                  (2, 'Locataire', 'Caution', 1),
                  (3, 'Locataire', 'Charges', 1),
                  (4, 'Locataire', 'Loyer', 1),
                  (10, 'Syndic', 'Appel de fonds', 10),
                  (11, 'Syndic', 'travaux', 10),
                  (12, 'Syndic', 'divers', 10),
                  (13, 'Syndic', 'charges', 10),
                  (14, 'Syndic', 'null', 10),
                  (20, 'Fournisseur', 'electricien', 20),
                  (21, 'Fournisseur', 'internet', 20),
                  (22, 'Fournisseur', 'telephone', 20),
                  (23, 'Fournisseur', 'informatique', 20),
                  (24, 'Fournisseur', 'Assurances', 20),
                  (25, 'Fournisseur', 'Banque', 20),
                  (26, 'Fournisseur', 'Restaurant', 20),
                  (27, 'Fournisseur', 'Parking', 20),
                  (28, 'Fournisseur', 'Comptabilité', 20),
                  (29, 'Fournisseur', 'Taxes', 20),
                  (30, 'Fournisseur', 'Fournitures', 20),
                  (31, 'Fournisseur', 'plombier', 20),
                  (32, 'Fournisseur', 'divers', 20),
                  (33, 'Fournisseur', 'Dépannage', 20),
                  (40, 'Associé', 'Capital', 40),
                  (41, 'Associé', 'Remboursement', 40),
                  (42, 'Associé', 'Frais kilomètriques', 40)]


dicoType = [("PRELEVEMENT", "COMMISSIONS PERCUES" ),
            ("VIREMENT", "VIREMENT INSTANTANE RECU" ),
            ("CB","PAIEMENT CB")]

dicoLocaux = [
    (1, "Saint Jean"),
    (2, "Estey 80"),
    (3, "Estey 31"),
    (4, "Estey 168"),
    (5, "Maucaillou"),
    (6, "Résid Godard"),
    (7, "Sainte Luce"),
    (8, "Frais généraux"),
    (9, "Billaudel"),
    (10, "Andernos")]


dicoFournisseurs = [(30, 'LEROY MERLIN'),
                    (21, 'FREE TELECOM'),
                    (23, 'ICONCEPT'),
                    (23, 'DARTY'),
                    (23, 'SUPSOFT'),
                    (23, 'BOULANGER'),
                    (24, 'MUTUELLE DE POITIERS'),
                    (28, 'AREVCO'),
                    (22, 'BOUYGUES'),
                    (30, 'BUT'),
                    (30, 'MDA'),
                    (30, 'AUCHAN'),
                    (30, 'TOP SERVICE'),
                    (26, 'Restaurant'),
                    (29, 'IMPÔTS'),
                    (27, 'EASYPARK'),
                    (21, 'ORANGE'),
                    (30, 'CHROMADIS'),
                    (30, 'LAPEYRE'),
                    (33, 'REPAR STORES'),
                    (33, 'ELECTRICIEN'),
                    (25, 'BNP'),
                    (32, 'LA POSTE'),
                    (32, 'GREFFE'),
                    (31, 'CCVP ENERGIE')]

dicoSyndicats = [(10, 5, 'JACQUART GESTION'),
                 (10, 7, 'Syndic Ste Luce'),
                 (10, 9, 'SYND BILLAUDEL'),
                 (10, 1, 'ACTIIM'),
                 (10, 6, 'LOFT ONE'),
                 (10, 10, 'BORE')]


dicoLocataires = [(2, 'VEURE Loic'),
                  (3, 'DENIERE Elise'),
                  (9, 'MENDES Elisa'),
                  (9, 'LAY Céline'),
                  (9, 'BERNARD Antoine'),
                  (4, 'NICITA Gabriele'),
                  (1, 'PEYRAT Alban'),
                  (1, 'GHIRARDO COURCIER'),
                  (7, 'SERVAS Benoit'),
                  (5, 'BLOSSIER Mathilde'),
                  (6, 'DENIS Lucas'),
                  (9, 'BOUVIER Léo')]

dicoAssocies = [(41, 'Comptes Associés'),
                (41, 'Comptes Associés'),
                (42, 'Frais Kilomètriques')]

mes_variables = {"sgbd": "Base.db"}

dicoTables = {"local": ["(id_local INTEGER, local TEXT,PRIMARY KEY(id_local AUTOINCREMENT))"],
              "categories": ["(id_categories INTEGER, categorie TEXT, sous_categorie TEXT, parent_id INTEGER DEFAULT 0,PRIMARY KEY(id_categories AUTOINCREMENT))"],
              "ecritures": ["(id_ecritures INTEGER, date TEXT, type TEXT, libelle TEXT, montant REAL, pointage INTEGER DEFAULT 0, id_categories INTEGER DEFAULT 0, id_local INTEGER DEFAULT 8,PRIMARY KEY(id_ecritures AUTOINCREMENT)FOREIGN KEY (id_categories) REFERENCES categories (id_categories)FOREIGN KEY(id_local) REFERENCES  local(id_local))"]}
